title: ELX 虚拟经济有限公司
email: microboym@icloud.com
description: >-
  发布违纪记录，有疑问可以咨询克服。
baseurl: "/elx"
url: ""
github_username:  microboym

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
